### PR TITLE
Spike (2) generating API to STDOUT

### PR DESCRIPTION
**Pull request by atifaziz**
@danielmarbach I am sharing a second tool that I started in the same spirit of addressing #173 before it was opened as an issue. I am sharing it as a spike in this PR. The reason I added a second tool is that I wasn't very hopeful that all the ideas would be welcome (sensing, perhaps falsely, some resistance with the other PRs I submitted) so I wanted a branch in my fork that I could always rebase or merge to keep up with the changes in this project. After all, the tools do very little and the bulk of the API generation is in the library so it seemed like an acceptable compromise in the interest of time. If you like what you see, I'd be happy to contribute.

I have done some other minor refactorings and changes to improve the output but those are completely secondary.

You are free to close this PR and I am happy to maintain my own fork but I'd rather collaborate and contribute back if the feedback and ideas are welcome.

### Multiple target frameworks

```
dotnet run -p .\src\PublicApiGenerator.Cli -- --package morelinq --package-version [3.3.0] --target-frameworks 'netcoreapp3.1;netcoreapp2.1'
```

output:

```
A:\PublicApiGenerator\morelinq.netcoreapp3.1.received.txt
A:\PublicApiGenerator\morelinq.netcoreapp2.1.received.txt
```

### Single target framework + `grep`

```
dotnet run -p .\src\PublicApiGenerator.Cli -- --package morelinq --package-version [3.3.0] --target-frameworks netcoreapp2.1 | grep Zip
```

output:

```
    public static class BatchExtension
        public static System.Collections.Generic.IEnumerable<System.Collections.Generic.IEnumerable<TSource>> Batch<TSource>(this System.Collections.Generic.IEnumerable<TSource> source, int size) { }
        public static System.Collections.Generic.IEnumerable<TResult> Batch<TSource, TResult>(this System.Collections.Generic.IEnumerable<TSource> source, int size, System.Func<System.Collections.Generic.IEnumerable<TSource>, TResult> resultSelector) { }
        public static System.Collections.Generic.IEnumerable<System.Collections.Generic.IEnumerable<TSource>> Batch<TSource>(this System.Collections.Generic.IEnumerable<TSource> source, int size) { }
        public static System.Collections.Generic.IEnumerable<TResult> Batch<TSource, TResult>(this System.Collections.Generic.IEnumerable<TSource> source, int size, System.Func<System.Collections.Generic.IEnumerable<TSource>, TResult> resultSelector) { }
```

### CODE REVIEW

**Comment by danielmarbach** [comment]
> The reason I added a second tool is that I wasn't very hopeful that all the ideas would be welcome (sensing, perhaps falsely, some resistance with the other PRs I submitted) so I wanted a branch in my fork that I could always rebase or merge to keep up with the changes in this project. After all, the tools do very little and the bulk of the API generation is in the library so it seemed like an acceptable compromise in the interest of time. 

> You are free to close this PR and I am happy to maintain my own fork but I'd rather collaborate and contribute back if the feedback and ideas are welcome.

Sorry if I have given you the impression your ideas are not welcome. I tried to say it multiple times that I really appreciate your input. That being said that doesn't mean I always agree with them ;)

Regarding this PR. Why did you introduce your changes in a separate CLI tool? Was the reason sooley that you could keep up with the changes in the generator tool in case your PR would not be taken?

In general I looked at the PR and I'm happy to take the changes you made for the generator tool because I was already aligned with your proposal in #173. Namely

> The tool would need two modes of operation:
> 
> 1. Generate API to standard output if only a single target framework is given and the `--output-directory` argument is absent.
> 2. Generate files per framework API like now but print the generate file paths to standard output.
> 
> If the `--output-directory` argument is supplied then it's clear that the user wants a file generated even if a single target framework is given, and in which case, the tool should enter mode 2.

I still though want the tool to support multiple target frameworks but as I saw your code has that still built in.

**Comment by atifaziz** [comment]
> I tried to say it multiple times that I really appreciate your input.

Absolutely, I acknowledge and appreciate that. ❤️ 

> That being said that doesn't mean I always agree with them ;)

It would be arrogant and unfair of me to expect that. 😄 

> Sorry if I have given you the impression your ideas are not welcome.

I think that sentiment was coming from two things:

- Your desire to maintain a backwards compatibility so it have been harder to push some ideas through
- PR #166 that was merged but overwritten with a [force-push](https://github.com/PublicApiGenerator/PublicApiGenerator/pull/166#event-2988960826), throwing away everything before

But all's good.

> Regarding this PR. Why did you introduce your changes in a separate CLI tool? Was the reason sooley that you could keep up with the changes in the generator tool in case your PR would not be taken?

Yes, that's right. I also needed to iterate quicker without being bound by compatibility decisions although I value those tremendously and do my best to maintain them in my projects too (so I know where you're coming from). I also felt that PublicApiGenerator might be designed primarily for approval tests audiences so opening it up for general-purpose use might cause conflicts.

> In general I looked at the PR and I'm happy to take the changes you made for the generator tool because I was already aligned with your proposal in #173.

Good to hear! I can work those changes back.

> I still though want the tool to support multiple target frameworks but as I saw your code has that still built in.

That's fair.

**Comment by danielmarbach** [comment]
> PR #166 that was merged but overwritten with a force-push, throwing away everything before

Yeah sorry for that. I created a local branch with the intention to do all the changes there. When I pushed it to upstream I had it on this repo. Then for some reason I forgot to switch the back to upstream when I force pushed. I would not have force pushed if I had been aware I'm doing it on your repo. Very sorry that was not cool. Will pay extra attention next time.

> But all's good.

Great to hear!

**Comment by atifaziz** [comment]
> Yeah sorry for that. I created a local branch with the intention to do all the changes there. When I pushed it to upstream I had it on this repo. Then for some reason I forgot to switch the back to upstream when I force pushed. I would not have force pushed if I had been aware I'm doing it on your repo. Very sorry that was not cool. Will pay extra attention next time.

Hey, no worries. I figured it was something like that or me getting it very wrong except I would have wanted to hear back in case of the latter to get the “spirit” of the project. It wasn't a life-changing contribution 🙃 that took me an entire evening so don't mean to make a whole hoo-ha about it. Moving forward, I am going to close this PR and submit the desirable bits as separate PRs based on the direction we agreed on.

**Pull request closed without merging**
